### ISSUE TITLE
Status 201 Problem

### ISSUE THREAD

**Issue by syvoid** [LukeHagar/plexpy#6]
This is a very simple example. I just used it to request the PIN Code, and then this error was returned.Is this a bug? Please help.
The plex-api-client version is 0.8.1

My code is:

import plex_api
def test1():
    s = plex_api.PlexAPI(
        access_token='p65asdfZWyA1fLTHgv1X'
    )
    res = s.plex.get_pin(strong=False, x_plex_client_identifier='8d15b989-fa40-4175-9336-953b1effd123')
    if res.object is not None:
        print(res.object)
        pass

The debug log:

Traceback (most recent call last):
  File "/home/user1/.pycharm_helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user1/proj1/test.py", line 15, in <module>
    test1()
  File "/home/user1/proj1/test.py", line 9, in test1
    res = s.plex.get_pin(strong=False, x_plex_client_identifier='8d15b989-fa40-4175-9336-953b1effd123')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/.virtualenvs/proj1/lib/python3.11/site-packages/plex_api/plex.py", line 91, in get_pin
    raise errors.SDKError('unknown status code received', http_res.status_code, http_res.text, http_res)
plex_api.models.errors.sdkerror.SDKError: unknown status code received: Status 201
{"id":1638197055,"code":"X45X","product":"0","trusted":false,"qr":"https://plex.tv/api/v2/pins/qr/X45H","clientIdentifier":"8d15b989-fa40-4175-9336-953b1effd123","location":{"code":"US","european_union_member":false,"continent_code":"NA","country":"United States","city":"Draper","time_zone":"America/Denver","postal_code":"84020","in_privacy_restricted_country":false,"subdivisions":"Utah","coordinates":"40.5084, -111.8838"},"expiresIn":900,"createdAt":"2024-06-12T19:53:38Z","expiresAt":"2024-06-12T20:08:38Z","authToken":null,"newRegistration":null}

**Comment by LukeHagar** [comment]
This is a bug!

Thank you, I have corrected the response to a `201` instead of a `200` in [#21](https://github.com/LukeHagar/plex-api-spec/pull/21)
