### ISSUE TITLE
X-Plex-Client-Identifier is missing

### ISSUE THREAD

**Issue by Commod0re** [LukeHagar/plexpy#7]
having trouble getting any of the code examples to work, no matter what I do I get `{"errors":[{"code":1000,"message":"X-Plex-Client-Identifier is missing","status":400}]}`

I even tried using one of the examples effectively verbatim:

```python
import getpass
from plex_api_client import PlexAPI

client = PlexAPI(
    client_id="gcgzw5rz2xovp84b4vha3a40",
    client_name="Plex Web",
    client_version="4.133.0",
    client_platform="Chrome",
    device_name="Linux",
)
res = client.authentication.post_users_sign_in_data(request={
    'login': 'email@address.redacted',
    'password': getpass.getpass('plex password'),
    #'verification_code': getpass.getpass('TOTP'),
})
```

```
Traceback (most recent call last):
  File "~/.pyenv/versions/3.10.7/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "~/.pyenv/versions/plex-playlist-sync/lib/python3.10/site-packages/plex_api_client/authentication.py", line 686, in post_users_sign_in_data
    raise errors.PostUsersSignInDataBadRequest(data=data)
plex_api_client.models.errors.post_users_sign_in_data.PostUsersSignInDataBadRequest: {"errors":[{"code":1000,"message":"X-Plex-Client-Identifier is missing","status":400}]}
```

am I doing something wrong here? what am I missing? is there any actual documentation anywhere? how long has this been broken? do y'all even test this thing? a handful of incomplete examples that don't actually work, a list of functions with almost no useful information... is this representative of the types of libraries you like to work with?

worst of all it's almost impossible to work around the poor documentation by reading the code because the code is super indirect and neither commented, nor written clearly enough to be self-documenting

what a frustrating mess

**Comment by LukeHagar** [comment]
Hey @Commod0re,

This SDK and all of the others listed [here](https://github.com/LukeHagar/plex-api-spec), are all generated from one OpenAPI specification. The CTO at Plex was kind enough to share a bunch of markdown documentation that I began converting to OpenAPI in effort to expand it further and better document the API. 

So far, I and two other individuals have contributed to it in our free time, and we welcome any assistance the community wants to provide!

> am I doing something wrong here? what am I missing? is there any actual documentation anywhere? 

The readme contains documentation for the methods and types present in the SDK, and additional API focused documentation can be found [here](https://plexapi.dev/api-reference). 

This documentation is also sourced from the same OpenAPI specification, so as we continue to expand and correct the OpenAPI specification it should also expand.

> how long has this been broken? 

That specific endpoint you mentioned was very recently added to the Spec, it looks like a required parameter just needs to be added

> do y'all even test this thing?

Some! Tests are all written manually in the main spec repo, so far only written by @Jasonlandbridge.

In the near future, we will be looking to add a few additional types of tests at different points to each generated SDK to validate some sets of functionality.

> a handful of incomplete examples that don't actually work, a list of functions with almost no useful information... is this representative of the types of libraries you like to work with?

This feedback feels less constructive. 

We have tried to piece together as much information on this API as we can using traditional data-gathering methods. Which In this context are pretty much exclusively reviewing calls in the network explorer inside a browser while interacting with the Plex website and by throwing API requests at the Plex fridge via Postman spaghetti style. 

If you have any specific knowledge you would like to share or if you want to contribute meaningfully we would welcome that. 

> worst of all it's almost impossible to work around the poor documentation by reading the code because the code is super indirect and neither commented, nor written clearly enough to be self-documenting

Again, this SDK, along with all the others linked are fully generated. Not hand written. It is just a few folks working to try and document the Plex API as thoroughly as possible, and provide SDKs for the community in as many languages as possible.

> what a frustrating mess

Have a wonderful day, and happy development!

**Comment by JasonLandbridge** [comment]
@LukeHagar You're too polite, I would have told this rude and ungrateful brat off.

**Comment by Commod0re** [comment]
you are right, I was wrong to allow my frustration to get the best of me, I apologize for being rude

**Comment by LukeHagar** [comment]
No worries @Commod0re, my goal is to document as much of the plex API as I can, and provide SDKs in an many languages as I can.

Time is definitely a factor for me, and I welcome any and all contributions!

**Comment by JasonLandbridge** [comment]
@Commod0re Thank you for your apology and admittedly, this project is still a very much a work in progress. If you happen to use Python then I can recommend [python-plexapi](https://github.com/pkkid/python-plexapi) which is a more mature project.
